# Copyright 2022-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
# The BSD-3-Clause license can be found at https://spdx.org/licenses/BSD-3-Clause.html


include(${CMAKE_SOURCE_DIR}/cmake/toolchain/arm-none-eabi.cmake)

set(COEX_NXP_LINKER_FILE      ${PROJECT_SOURCE_DIR}/examples/linker/RW61x_flash.ld)
set(COEX_NXP_APP_CONFIG_FILE  ${PROJECT_SOURCE_DIR}/boards/${COEX_NXP_PLATFORM}/app_config.h)

set(COEX_NXP_APP_CONFIG_bt_ble " \
    -include ${COEX_NXP_APP_CONFIG_FILE} \
    -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 \
    -DUSE_RTOS=1 \
    -DPRINTF_ADVANCED_ENABLE=1 \
    -DSDK_OS_FREE_RTOS \
    -DFSL_OSA_TASK_ENABLE=1 \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DGATT_DB \
    -DGATT_CLIENT \
    -DCONFIG_BT_SNOOP=1 \
    -DDEBUG_CONSOLE_SCANF_MAX_LOG_LEN=64 \
    -DCONFIG_BT_SETTINGS \
    -DAPPL_LIMIT_LOGS \
    -DBT_SNOOP_WRITE_TRUNCATE \
    -DNXP_CODE \
    -DOSA_USED \
    -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 \
    -DAPPL_CONFIG_DISABLE \
    -DPXM \
    -DHTS \
    -DBT_PLATFORM \
    -DEDGEFAST_BT_LITTLEFS_MFLASH \
    -DAPPL_MENU_OPS \
    -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE \
    -DSAI_XFER_QUEUE_SIZE=6 \
    -DSDK_COMPONENT_INTEGRATION=1 \
    -DIPSP_HAVE_6LO_NIFACE \
    -DLWIP_IPV6 \
    -DSUPPORT_HTTP_CLIENT \
    -DFSL_OSA_MAIN_FUNC_ENABLE=0 \
    -DLE_AUDIO_ENABLE_PRINTS_FOR_STREAMING=1 \
    -DAPPL_GAP_CENTRAL \
    -DAPPL_GAP_PERIPHERAL \
    -DAPPL_NEW_THREAD_POST_MSG \
    -DHAL_UART_ADAPTER_FIFO=1 \
    -DHAL_UART_ISR_PRIORITY=configLIBRARY_LOWEST_INTERRUPT_PRIORITY \
    -DSTORAGE_IDLE_TASK_SYNC_ENABLE=1 \
    -DNVRAM_WORKAROUND \
    -DSERIAL_MANAGER_TASK_PRIORITY=3 \
    -DSERIAL_MANAGER_TASK_STACK_SIZE=4096 \
    -DAPP_FLEXSPI_AMBA_BASE=134217728 \
    -DMinimalHeapSize_c=262144 \
    -DDEBUG_CONSOLE_ENABLE_ECHO \
    -DAPPL_LOWPOWER_ENABLED=1 \
    -DAPP_CONFIG_ENABLE_MALLOC_FAILURE_FREERTOS_HOOK=1 \
    -DAPP_CONFIG_ENABLE_STACK_OVERFLOW_FREERTOS_HOOK=1 \
    -DLC3_DSP=0 \
    -DGATT_SERVER \
    -DCFG_BLE \
    -DCPU_RW612ETA2I \
    -DMCUXPRESSO_SDK \
    -DBOOT_HEADER_ENABLE=1 \
    -DSERIAL_PORT_TYPE_UART=1 \
    -DMFLASH_FILE_BASEADDR=7340032 \
    -DLFS_CONFIG=fwk_lfs_config.h \
    -DHAL_UART_ADAPTER_LOWPOWER=1 \
    -DSBTSNOOP_PORT_FILE=sbtsnoop_port_ethermind.h \
    -DSERIAL_BTSNOOP \
    -DMBEDTLS_MCUX_ELS_PKC_API \
    -DMBEDTLS_MCUX_USE_PKC \
    -DLWIP_DISABLE_PBUF_POOL_SIZE_SANITY_CHECKS=1 \
    -DCHECKSUM_GEN_ICMP6=1 \
    -DCHECKSUM_CHECK_ICMP6=1 \
    -DLWIP_TIMEVAL_PRIVATE=0 \
    -DSO_REUSE=1 \
    -DGENERIC_LIST_LIGHT=1 \
    -DMBEDTLS_MCUX_ELS_API \
    -DMBEDTLS_MCUX_USE_ELS \
    -DMCUXCL_FEATURE_CSSL_MEMORY_C_FALLBACK \
    -DLWIP_DNS=1 \
    -DLWIP_NETIF_HOSTNAME=1 \
    -DLWIP_IGMP=1 \
    -D_XOPEN_SOURCE=500 \
    -DMBEDTLS_THREADING_C \
    -DMBEDTLS_THREADING_ALT \
")

set(COEX_NXP_APP_CONFIG_bt_ble_only " \
    -include ${COEX_NXP_APP_CONFIG_FILE} \
    -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 \
    -DUSE_RTOS=1 \
    -DPRINTF_ADVANCED_ENABLE=1 \
    -DSDK_OS_FREE_RTOS \
    -DFSL_OSA_TASK_ENABLE=1 \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DGATT_DB \
    -DGATT_CLIENT \
    -DCONFIG_BT_SNOOP=1 \
    -DDEBUG_CONSOLE_SCANF_MAX_LOG_LEN=64 \
    -DCONFIG_BT_SETTINGS \
    -DBT_SNOOP_WRITE_TRUNCATE \
    -DNXP_CODE \
    -DOSA_USED \
    -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1 \
    -DAPPL_CONFIG_DISABLE \
    -DPXM \
    -DHTS \
    -DBT_PLATFORM \
    -DEDGEFAST_BT_LITTLEFS_MFLASH \
    -DAPPL_MENU_OPS \
    -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE \
    -DSAI_XFER_QUEUE_SIZE=6 \
    -DSDK_COMPONENT_INTEGRATION=1 \
    -DIPSP_HAVE_6LO_NIFACE \
    -DLWIP_IPV6 \
    -DSUPPORT_HTTP_CLIENT \
    -DFSL_OSA_MAIN_FUNC_ENABLE=0 \
    -DAPPL_GAP_CENTRAL \
    -DAPPL_GAP_PERIPHERAL \
    -DAPPL_NEW_THREAD_POST_MSG \
    -DHAL_UART_ADAPTER_FIFO=1 \
    -DHAL_UART_ISR_PRIORITY=configLIBRARY_LOWEST_INTERRUPT_PRIORITY \
    -DSTORAGE_IDLE_TASK_SYNC_ENABLE=1 \
    -DNVRAM_WORKAROUND \
    -DSERIAL_MANAGER_TASK_PRIORITY=3 \
    -DSERIAL_MANAGER_TASK_STACK_SIZE=4096 \
    -DAPP_FLEXSPI_AMBA_BASE=134217728 \
    -DMinimalHeapSize_c=262144 \
    -DDEBUG_CONSOLE_ENABLE_ECHO \
    -DAPP_LOWPOWER_ENABLED=1 \
    -DAPP_CONFIG_ENABLE_MALLOC_FAILURE_FREERTOS_HOOK=1 \
    -DAPP_CONFIG_ENABLE_STACK_OVERFLOW_FREERTOS_HOOK=1 \
    -DLC3_DSP=0 \
    -DGATT_SERVER \
    -DCFG_BLE \
    -DCPU_RW612ETA2I \
    -DMCUXPRESSO_SDK \
    -DBOOT_HEADER_ENABLE=1 \
    -DSERIAL_PORT_TYPE_UART=1 \
    -DMFLASH_FILE_BASEADDR=7340032 \
    -DLFS_CONFIG=fwk_lfs_config.h \
    -DHAL_UART_ADAPTER_LOWPOWER=1 \
    -DSBTSNOOP_PORT_FILE=sbtsnoop_port_ethermind.h \
    -DSERIAL_BTSNOOP \
    -DMBEDTLS_MCUX_ELS_PKC_API \
    -DMBEDTLS_MCUX_USE_PKC \
    -DLWIP_DISABLE_PBUF_POOL_SIZE_SANITY_CHECKS=1 \
    -DCHECKSUM_GEN_ICMP6=1 \
    -DCHECKSUM_CHECK_ICMP6=1 \
    -DLWIP_TIMEVAL_PRIVATE=0 \
    -DSO_REUSE=1 \
    -DGENERIC_LIST_LIGHT=1 \
    -DMBEDTLS_MCUX_ELS_API \
    -DMBEDTLS_MCUX_USE_ELS \
    -DMCUXCL_FEATURE_CSSL_MEMORY_C_FALLBACK \
    -DLWIP_DNS=1 \
    -DLWIP_NETIF_HOSTNAME=1 \
    -DLWIP_IGMP=1 \
    -D_XOPEN_SOURCE=500 \
    -DMBEDTLS_THREADING_C \
    -DMBEDTLS_THREADING_ALT \
")

set(COEX_NXP_APP_CONFIG_edgefast " \
    -include ${COEX_NXP_APP_CONFIG_FILE} \
    -DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1 \
    -DGATT_CLIENT \
    -DGATT_DB \
    -DFSL_DRIVER_TRANSFER_DOUBLE_WEAK_IRQ=0 \
    -DFSL_OSA_MAIN_FUNC_ENABLE=0 \
    -DFSL_FEATURE_FLASH_PAGE_SIZE_BYTES=4096 \
    -DgMemManagerLight=0 \
    -DCFG_BLE \
    -DgPlatformDisableBleLowPower_d=1 \
    -DUSE_RTOS=1 \
    -DPRINTF_ADVANCED_ENABLE=1 \
    -DSDK_OS_FREE_RTOS \
    -DFSL_OSA_TASK_ENABLE=1 \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DCONFIG_BT_BREDR=1 \
    -DCONFIG_BT_PERIPHERAL=1 \
    -DCONFIG_BT_CENTRAL=1 \
    -DCONFIG_BT_SMP=1 \
    -DCONFIG_BT_GATT_CLIENT=1 \
    -DSHELL_TASK_STACK_SIZE=6144 \
    -DLPUART_RING_BUFFER_SIZE=1024U \
    -DHAL_AUDIO_DMA_INIT_ENABLE=0 \
    -DLFS_NO_INTRINSICS=1 \
    -DLFS_NO_ERROR=1 \
    -DCONFIG_ARM=1 \
    -DBT_PLATFORM \
    -DEDGEFAST_BT_LITTLEFS_MFLASH \
    -DCPU_RW612ETA2I \
    -DMCUXPRESSO_SDK \
    -DBOOT_HEADER_ENABLE=1 \
    -DSHELL_ADVANCE=1 \
    -DDEBUG_CONSOLE_RX_ENABLE=0 \
    -DOSA_USED=1 \
    -DSHELL_USE_COMMON_TASK=0 \
    -DLOG_ENABLE_ASYNC_MODE=1 \
    -DLOG_MAX_ARGUMENT_COUNT=10 \
    -DLOG_ENABLE_OVERWRITE=0 \
    -DSERIAL_PORT_TYPE_UART=1 \
    -DMFLASH_FILE_BASEADDR=7340032 \
    -DMBEDTLS_MCUX_ELS_PKC_API \
    -DMBEDTLS_MCUX_USE_PKC \
    -DMBEDTLS_MCUX_ELS_API \
    -DMBEDTLS_MCUX_USE_ELS \
    -DMCUXCL_FEATURE_CSSL_MEMORY_C_FALLBACK \
    -DSHELL_TASK_PRIORITY=1 \
    -DMBEDTLS_THREADING_C \
    -DMBEDTLS_THREADING_ALT \
")
if ((${COEX_ENABLE_WIFI} MATCHES OFF) AND (${COEX_ENABLE_BLE} MATCHES ON) AND
    (${COEX_ENABLE_OT} MATCHES OFF) AND (${COEX_NXP_BASE} MATCHES bt_ble))
set(COEX_NXP_APP_CONFIG ${COEX_NXP_APP_CONFIG_bt_ble_only})
else ()
set(COEX_NXP_APP_CONFIG ${COEX_NXP_APP_CONFIG_${COEX_NXP_BASE}})
endif ()

message(STATUS "${COEX_NXP_APP_CONFIG}")

include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)

include(${NXP_SDK_ROOT}/tools/cmake_toolchain_files/mcux_config.cmake)

# coex-nxp config
set(COEX_NXP_EXPORT_TO_BIN ON CACHE BOOL "")
set(COEX_APP_SUPP OFF CACHE BOOL "")
set(COEX_USE_EXTERNAL_OT_LIB OFF CACHE BOOL "")
set(COEX_ENABLE_WIFI ON CACHE BOOL "")
set(COEX_ENABLE_BLE ON CACHE BOOL "")
set(COEX_ENABLE_OT OFF CACHE BOOL "")
