/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i] Mask for item 13. */
#define MCI_IO_MUX_GPIO_GRP0_SEL_13_MASK 0x2000u
/*!
 * @brief pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i] Mask for item 14. */
#define MCI_IO_MUX_GPIO_GRP0_SEL_14_MASK 0x4000u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[21:0] Mask for item 13. */
#define SOCCIU_MCI_IOMUX_EN0_EN_21_0_13_MASK 0x2000u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[21:0] Mask for item 14. */
#define SOCCIU_MCI_IOMUX_EN0_EN_21_0_14_MASK 0x4000u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M33 */

/*! @name GPIO_0 (coord M1), J1[14]/LED_BLUE
  @{ */
/* Routed pin properties */
#define BOARD_LED_BLUE_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_LED_BLUE_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_LED_BLUE_CHANNEL 0                          /*!<@brief Signal channel */
#define BOARD_LED_BLUE_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_BLUE_GPIO_PIN 0U                        /*!<@brief GPIO pin number */
#define BOARD_LED_BLUE_PORT 0U                            /*!<@brief PORT number */
#define BOARD_LED_BLUE_PIN 0U                             /*!<@brief PORT pin number */
#define BOARD_LED_BLUE_PIN_MASK (1U << 0U)                /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name GPIO_1 (coord N2), J5[1]/LED_RED
  @{ */
/* Routed pin properties */
#define BOARD_LED_RED_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_LED_RED_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_LED_RED_CHANNEL 1                          /*!<@brief Signal channel */
#define BOARD_LED_RED_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_RED_GPIO_PIN 1U                        /*!<@brief GPIO pin number */
#define BOARD_LED_RED_PORT 0U                            /*!<@brief PORT number */
#define BOARD_LED_RED_PIN 1U                             /*!<@brief PORT pin number */
#define BOARD_LED_RED_PIN_MASK (1U << 1U)                /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name GPIO_12 (coord N8), LED_GREEN
  @{ */
/* Routed pin properties */
#define BOARD_LED_GREEN_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_LED_GREEN_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_LED_GREEN_CHANNEL 12                         /*!<@brief Signal channel */
#define BOARD_LED_GREEN_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN_GPIO_PIN 12U                       /*!<@brief GPIO pin number */
#define BOARD_LED_GREEN_PORT 0U                            /*!<@brief PORT number */
#define BOARD_LED_GREEN_PIN 12U                            /*!<@brief PORT pin number */
#define BOARD_LED_GREEN_PIN_MASK (1U << 12U)               /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M33 */

/*! @name GPIO_11 (coord M2), J1[6]
  @{ */
/* Routed pin properties */
#define BOARD_SW2_PERIPHERAL GPIO                   /*!<@brief Peripheral name */
#define BOARD_SW2_SIGNAL PIO0                       /*!<@brief Signal name */
#define BOARD_SW2_CHANNEL 11                        /*!<@brief Signal channel */
#define BOARD_SW2_GPIO GPIO                         /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW2_GPIO_PIN 11U                      /*!<@brief GPIO pin number */
#define BOARD_SW2_PORT 0U                           /*!<@brief PORT number */
#define BOARD_SW2_PIN 11U                           /*!<@brief PORT pin number */
#define BOARD_SW2_PIN_MASK (1U << 11U)              /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitNETPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSBPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTEMP_SENSORPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLASHPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPSRAMPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
